[theme.custom]
accent = "#00ABD1"
panel_bg = "#212527"
sidebar_bg = "#101416"
active_row_bg = "#333739"
selection_bg = "#464A4C"
surface0 = "#212527"
surface1 = "#333739"
surface_dim = "#101416"
overlay0 = "#464A4C"
overlay1 = "#5A5E60"
text = "#B0B5B6"
subtext0 = "#84888A"
mauve = "#00ABD1"
green = "#4DB073"
yellow = "#B49C43"
red = "#EC7D71"
blue = "#52A1F4"
teal = "#00B2CA"
peach = "#D78C50"
