[theme.custom]
accent = "#C0965B"
panel_bg = "#262422"
sidebar_bg = "#151310"
active_row_bg = "#383634"
selection_bg = "#4C4946"
surface0 = "#262422"
surface1 = "#383634"
surface_dim = "#151310"
overlay0 = "#4C4946"
overlay1 = "#5F5D5A"
text = "#B6B3B0"
subtext0 = "#8A8784"
mauve = "#C0965B"
green = "#4DB073"
yellow = "#B49C43"
red = "#EC7D71"
blue = "#52A1F4"
teal = "#00B2CA"
peach = "#D78C50"
