[theme.custom]
accent = "#789EE0"
panel_bg = "#232427"
sidebar_bg = "#121316"
active_row_bg = "#353639"
selection_bg = "#48494C"
surface0 = "#232427"
surface1 = "#353639"
surface_dim = "#121316"
overlay0 = "#48494C"
overlay1 = "#5C5D60"
text = "#B2B4B7"
subtext0 = "#86878B"
mauve = "#789EE0"
green = "#4DB073"
yellow = "#B49C43"
red = "#EC7D71"
blue = "#52A1F4"
teal = "#00B2CA"
peach = "#D78C50"
